// Generates src/components/icons.generated.ts from the installed Remix Icon set.
//
// All the icons we use are uniform (viewBox "0 0 24 24", a single <path>), so the whole set is
// emitted as one { name: pathData } map and bundled straight into the JS. That means the entire
// icon set ships inside the hashed JS chunk — no per-icon /assets request, and it rides the same
// immutable, CDN-cacheable bundle as the rest of the app (see <Icon>).
//
// Source of truth for which icons ship is the `iconNames` allowlist below. To add one: drop its
// Remix name in here (keep the list tidy) and re-run `npm run generate-icons -w @imageshow/web`
// (this also runs automatically in the web `prebuild`). The script fails loudly if a name isn't
// in the installed remixicon package, or if an icon isn't a single <path> (which the inline
// path-map can't represent) — so a Remix update that reshapes an icon can't slip through.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, "..");          // packages/web
const repo = resolve(pkg, "..", "..");    // repo root
const outFile = resolve(pkg, "src", "components", "icons.generated.ts");

// The icon allowlist — the single source of truth for which Remix icons ship. Keep sorted.
const iconNames = [
  "add-line",
  "arrow-down-s-line",
  "arrow-go-back-line",
  "arrow-left-right-line",
  "check-line",
  "checkbox-circle-line",
  "close-line",
  "dashboard-line",
  "database-2-line",
  "delete-bin-6-line",
  "delete-bin-7-line",
  "download-cloud-2-line",
  "drag-move-2-fill",
  "external-link-line",
  "eye-line",
  "eye-off-line",
  "file-copy-line",
  "file-damage-line",
  "filter-3-line",
  "fingerprint-line",
  "flask-line",
  "group-line",
  "hard-drive-2-line",
  "home-4-line",
  "image-line",
  "information-line",
  "key-2-line",
  "logout-box-r-line",
  "menu-line",
  "palette-line",
  "pencil-line",
  "price-tag-3-line",
  "quill-pen-line",
  "refresh-line",
  "save-3-line",
  "scales-3-line",
  "settings-3-line",
  "shuffle-line",
  "star-fill",
  "star-line",
  "upload-cloud-2-line",
  "user-add-line"
];

// Locate the installed remixicon package (hoisted to the repo root, or nested under the workspace).
const remixDir = [
  resolve(repo, "node_modules", "remixicon"),
  resolve(pkg, "node_modules", "remixicon")
].find(existsSync);
if (!remixDir) throw new Error("remixicon is not installed — run `npm install` first");

// Remix groups its icons in category sub-folders, so index every basename -> its SVG file path.
async function indexSvgsByName(root) {
  const index = new Map();
  async function walk(dir) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const full = resolve(dir, entry.name);
      if (entry.isDirectory()) await walk(full);
      else if (entry.name.endsWith(".svg")) index.set(entry.name.replace(/\.svg$/, ""), full);
    }
  }
  await walk(root);
  return index;
}

const svgByName = await indexSvgsByName(resolve(remixDir, "icons"));

const entries = [];
for (const name of [...iconNames].sort()) {
  const file = svgByName.get(name);
  if (!file) throw new Error(`Missing Remix Icon SVG: ${name}`);
  const svg = await readFile(file, "utf8");
  // Every drawable element in the file (excluding the <svg> wrapper). We only support a single
  // <path>, so anything else means this icon can't be represented as a bare `d` string.
  const drawables = [...svg.matchAll(/<(path|circle|rect|g|polygon|line|ellipse|polyline)\b/g)];
  const pathData = svg.match(/<path\b[^>]*\bd="([^"]+)"/);
  if (drawables.length !== 1 || !pathData) {
    throw new Error(`Icon "${name}" is not a single <path> (found ${drawables.length} drawable element(s)); the inline path-map can't represent it`);
  }
  entries.push([name, pathData[1]]);
}

const body = entries.map(([name, d]) => `  ${JSON.stringify(name)}: ${JSON.stringify(d)}`).join(",\n");
const out = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// The Remix Icon set inlined as a single { name: pathData } map and bundled into the JS, so the
// whole icon set ships in the hashed JS chunk (no per-icon /assets request; fully CDN/immutable-
// cacheable). Each value is the \`d\` of a "0 0 24 24" single-path icon, rendered inline by <Icon>
// with fill: currentColor. To change the set, edit the allowlist in scripts/generate-icons.mjs
// and re-run \`npm run generate-icons -w @imageshow/web\` (also runs in the web prebuild).
export const ICONS = {
${body}
} as const;

export type IconName = keyof typeof ICONS;
`;

await writeFile(outFile, out);
console.log(`generate-icons: wrote ${entries.length} icons to ${outFile.replace(repo, ".")}`);
